#! /bin/sh

MACH=`uname -i`

unset PYTHONHOME
unset PYTHONPATH

export MACHROOT=$HOME/mach/$MACH/pool

export PATH=$MACHROOT/bin:$HOME/pool/bin:$PATH
export MANPATH=$MACHROOT/man:$MANPATH
export LD_LIBRARY_PATH=$MACHROOT/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MACHROOT/lib:$LIBRARY_PATH
export CPATH=$MACHROOT/include:$CPATH
