#! /bin/sh

MACH=`hostname -s`

export MACHROOT=$HOME/mach/$MACH/pool

export PATH=$MACHROOT/bin:$PATH
export MANPATH=$MACHROOT/man:$MANPATH
export LD_LIBRARY_PATH=$MACHROOT/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MACHROOT/lib:$LIBRARY_PATH
export CPATH=$MACHROOT/include:$CPATH
